title:            Dynamics AX Development
description:      Education is not preparation for life, education is life itself.


# put your disqus here
disqus_shortname: https-dynamics365-github-io
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://Dynamics365.github.io

#max
github_username:  Dynamics365
linkedin: https://vn.linkedin.com/in/luannx
skype_id: luannxhcm2010
stackoverflow_id: 2165261
upwork: ~011ecdc758e7bc20b7
#end max
# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example

menu:
  - title: 'About'
    url: 'http://dynamics365.github.io/about'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'Favorites'
    url: '#'
    submenu:
      - title: 'OOPs Basic'
        url: '/intro/oops-basic/'
      - title: 'C# and X++'
        url: '/intro/csharp-and-xpp/'

# Owner/author information
owner:
  name:           Max Nguyen
  site:           http://axdeveloping.com
  avatar:         images/avatar.jpg
  bio:            "My name is Max, Dynamics AX Technical Consultant"
  email:          luan52@outlook.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: infanprodigy # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: dynamics365

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: ""

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/dynamics365"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/luannx"
  - title: "youtube"
    url: "https://www.youtube.com/user/Dota2012dota"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-57379422-3
google_verify: 
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
